apiVersion: apps/v1
kind: Deployment
metadata:
  name: komaldhote123-deploy
  labels:
    app: komaldhote123-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: komaldhote123-app
  template:
    metadata:
      labels:
        app: komaldhote123-app
    spec:
      containers:
      - name: komaldhote123-container
        image: komaldhote123/sa-mywabappsvc:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: komaldhote123-np-service
  labels:
    app: komaldhote123-np-app
spec:
  selector:
    app: komaldhote123-deploy-lbl

